DELETE http://localhost:5000/api/admin/users/68d5cb3dca212738c0ec1601
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ZGQzYTU2MjdkNGIyN2I2MWI2YTdiNCIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTQxMTAyNywiZXhwIjoxNzYyMDAzMDI3fQ.hQxB6fXOAbIXTnizbMXFE9in5gGFWjUHjraqVeT3efI
Content-Type: application/json